# Generated by Django 6.0.6 on 2026-07-07 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
        ('geo', '0002_location_updated_at_location_unique_location_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Amenity',
                'verbose_name_plural': 'Amenities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Optional icon name, for example: beach, hotel, restaurant', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DestinationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='destination_gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility and SEO', max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='destination',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='slug',
            field=models.SlugField(max_length=220, unique=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='destinations', to='destinations.amenity'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destinations', to='destinations.category'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['slug'], name='destination_slug_528bb8_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['is_featured'], name='destination_is_feat_54f559_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['is_active'], name='destination_is_acti_09f11c_idx'),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='destinations.destination'),
        ),
    ]
