# Generated by Django 6.0.6 on 2026-07-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_amenity_category_destinationimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='opening_hours',
            field=models.CharField(blank=True, help_text="Free-text display hours, e.g. '11:00 AM - 10:00 PM' or 'Open 24 hours' or 'Varies by season'", max_length=150),
        ),
    ]
