# Generated by Django 6.0.6 on 2026-07-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_destination_opening_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='is_owner_submitted',
            field=models.BooleanField(default=False, help_text='True when this listing came in through the public business self-registration form, rather than being added by staff via the admin.'),
        ),
        migrations.AddField(
            model_name='destination',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='destination',
            name='owner_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='destination',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
