# Generated by Django 6.0.6 on 2026-07-23 07:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_destination_is_owner_submitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='edit_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Private token that lets the owner edit this listing without an account. Never shown publicly - only returned once, at registration time.', unique=True),
        ),
    ]
