# Generated by Django 6.0.6 on 2026-07-01 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('meta_description', models.TextField()),
                ('meta_keywords', models.TextField()),
                ('h1_heading', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('destination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='destinations.destination')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
