# Generated by Django 6.0.6 on 2026-07-07 10:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('destinations', '0002_amenity_category_destinationimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='canonical_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landingpage',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='destination',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landing_page', to='destinations.destination'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='meta_description',
            field=models.CharField(max_length=320),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='meta_keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='landingpage',
            index=models.Index(fields=['slug'], name='api_landing_slug_a5528c_idx'),
        ),
        migrations.AddIndex(
            model_name='landingpage',
            index=models.Index(fields=['is_published'], name='api_landing_is_publ_05d59a_idx'),
        ),
    ]
