# Generated by Django 6.0.6 on 2026-07-01 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('Google Flights', 'Google Flights'), ('Booking.com', 'Booking.com'), ('Skyscanner', 'Skyscanner')], max_length=50)),
                ('booking_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_links', to='destinations.destination')),
            ],
            options={
                'ordering': ['provider'],
            },
        ),
    ]
