# Generated by Django 6.0.6 on 2026-07-07 10:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinglink',
            options={'ordering': ['display_order', 'provider']},
        ),
        migrations.AddField(
            model_name='bookinglink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookinglink',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookinglink',
            name='label',
            field=models.CharField(blank=True, help_text='Optional button label, for example: Book Hotel', max_length=100),
        ),
        migrations.AddField(
            model_name='bookinglink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bookinglink',
            name='booking_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bookinglink',
            name='provider',
            field=models.CharField(choices=[('google_flights', 'Google Flights'), ('booking_com', 'Booking.com'), ('skyscanner', 'Skyscanner'), ('expedia', 'Expedia'), ('other', 'Other')], max_length=50),
        ),
    ]
